# Generated by Django 3.0.3 on 2020-02-25 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('short_name', models.CharField(max_length=250, verbose_name='Короткое наименование')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('version', models.CharField(max_length=250, verbose_name='Версия')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Дата начала действия версии')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250, verbose_name='Код элемента')),
                ('value', models.CharField(max_length=250, verbose_name='Значение элемента')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Directory', verbose_name='родительский идентификатор')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
                'ordering': ['code'],
            },
        ),
    ]
