# Generated by Django 3.0.3 on 2020-02-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200225_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='version',
            field=models.CharField(max_length=250, unique=True, verbose_name='Версия'),
        ),
    ]
