# Generated by Django 3.0.3 on 2020-02-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20200225_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='start_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата начала действия версии'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.Directory', verbose_name='родительский справочник'),
        ),
    ]
