# Generated by Django 3.0.3 on 2020-02-26 03:40

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_auto_20200225_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='directory_id',
            field=models.IntegerField(default=0, verbose_name='Идентификатор справочника'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='version',
            field=models.CharField(max_length=250, unique_for_year=builtins.id, verbose_name='Версия'),
        ),
    ]
