# Generated by Django 3.0.3 on 2020-02-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0010_unit_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='parent_id',
        ),
    ]
